name: Trigger auto deployment for template-dotnet-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/template-dotnet-api-AutoDeployTrigger-3effc1c2-e301-4b50-b333-22a170a52963.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TEMPLATEDOTNETAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEMPLATEDOTNETAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEMPLATEDOTNETAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}TemplateAPI
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.TEMPLATEDOTNETAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEMPLATEDOTNETAPI_REGISTRY_PASSWORD }}
          containerAppName: template-dotnet-api
          resourceGroup: TemplateDotNetAPI
          imageToBuild: ghcr.io/template-dotnet-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


